In [5]:
import pandas as pd

%matplotlib inline

In [6]:
df = pd.read_csv('../data/7dotS39_ALL_nocuts_extendedFMT.txt', skiprows=1)

def process_andrea_data(data_path):
    
    df = pd.read_csv(data_path, skiprows=1)
    
    if data_path == "../data/7dotS39_ALL_FiorenzoFMT.txt":
    
        vals = [df.iloc[:, 0].loc[x].split() for x in df.index]
        kic = [vals[x][0] for x in range(len(vals))]
      # ra = [vals[x][1] for x in range(len(vals))] this is not ra, dec
      # dec = [vals[x][2] for x in range(len(vals))]
        feh = [vals[x][3] for x in range(len(vals))]
        afe = [vals[x][4] for x in range(len(vals))]
        age = [vals[x][5] for x in range(len(vals))]
        age_68l = [vals[x][6] for x in range(len(vals))]
        age_68u = [vals[x][7] for x in range(len(vals))]
        mass = [vals[x][8] for x in range(len(vals))]
        mass_68l = [vals[x][9] for x in range(len(vals))]
        mass_68u = [vals[x][10] for x in range(len(vals))]
        evstate = [vals[x][11] for x in range(len(vals))]
        
        new_df = pd.DataFrame()

        new_df['KIC'] = kic
       # new_df['RA'] = ra
       # new_df['DEC'] = dec
        new_df['feh'] = feh
        new_df['afe'] = afe
        new_df['age'] = age
        new_df['age_68L'] = age_68l
        new_df['age_68U'] = age_68u
        new_df['mass'] = mass
        new_df['mass_68L'] = mass_68l
        new_df['mass_68U'] = mass_68u
        new_df['evstate'] = evstate
        
    elif data_path == "../data/7dotS39_ALL_nocuts_extendedFMT.txt":
        
        vals = [df.iloc[:, 0].loc[x].split() for x in df.index]
        
        apogee_id = [vals[x][0] for x in range(len(vals))]
        kic = [vals[x][1] for x in range(len(vals))]
        ra = [vals[x][2] for x in range(len(vals))]
        dec = [vals[x][3] for x in range(len(vals))]
        feh = [vals[x][4] for x in range(len(vals))]
        afe = [vals[x][5] for x in range(len(vals))]
        age = [vals[x][6] for x in range(len(vals))]
        age_68l = [vals[x][7] for x in range(len(vals))]
        age_68u = [vals[x][8] for x in range(len(vals))]
        mass = [vals[x][9] for x in range(len(vals))]
        mass_68l = [vals[x][10] for x in range(len(vals))]
        mass_68u = [vals[x][11] for x in range(len(vals))]
        dist = [vals[x][12] for x in range(len(vals))]
        dist_68L = [vals[x][13] for x in range(len(vals))]
        dist_68U = [vals[x][14] for x in range(len(vals))]
        Av = [vals[x][15] for x in range(len(vals))]
        Av_68L = [vals[x][16] for x in range(len(vals))]
        Av_68U = [vals[x][17] for x in range(len(vals))]
        evstate = [vals[x][18] for x in range(len(vals))]
        
        new_df = pd.DataFrame()
        new_df['APOGEE_ID'] = apogee_id
        new_df['KIC'] = kic
        new_df['RA'] = ra
        new_df['DEC'] = dec
        new_df['feh'] = feh
        new_df['afe'] = afe
        new_df['age'] = age
        new_df['age_68L'] = age_68l
        new_df['age_68U'] = age_68u
        new_df['mass'] = mass
        new_df['mass_68L'] = mass_68l
        new_df['mass_68U'] = mass_68u      
        new_df['dist'] = dist
        new_df['dist_68L'] = dist_68L
        new_df['dist_68U'] = dist_68U
        new_df['Av'] = Av
        new_df['Av_68L'] = Av_68L
        new_df['Av_68U'] = Av_68U
        new_df['evstate'] = evstate
        
    else:
        pass
    
    return new_df

In [7]:
nocut = "../data/7dotS39_ALL_nocuts_extendedFMT.txt"
cut = "../data/7dotS39_ALL_FiorenzoFMT.txt"

In [8]:
cut_andrea = process_andrea_data(cut)
nocut_andrea = process_andrea_data(nocut)

merged = pd.merge(cut_andrea, nocut_andrea, on="KIC")

df_merged = merged.drop(['feh_y', 'afe_y', 'age_y', 'age_68L_y',
       'age_68U_y', 'mass_y', 'mass_68L_y', 'mass_68U_y', 'evstate_y'], axis=1)

clean_df = pd.DataFrame()

clean_df["APOGEE_ID"] = df_merged["APOGEE_ID"]
clean_df["KIC"] = df_merged["KIC"]
clean_df["RA"] = df_merged["RA"]
clean_df["DEC"] = df_merged["DEC"]
clean_df["feh"] = df_merged["feh_x"]
clean_df["afe"] = df_merged["afe_x"]
clean_df["age"] = df_merged["age_x"]
clean_df["age_68L"] = df_merged["age_68L_x"]
clean_df["age_68U"] = df_merged["age_68U_x"]
clean_df["mass"] = df_merged["mass_x"]
clean_df["mass_68L"] = df_merged["mass_68L_x"]
clean_df["mass_68U"] = df_merged["mass_68U_x"]
clean_df["dist"] = df_merged["dist"]
clean_df["dist_68L"] = df_merged["dist_68L"]
clean_df["dist_68U"] = df_merged["dist_68U"]
clean_df["Av"] = df_merged["Av"]
clean_df["Av_68L"] = df_merged["Av_68L"]
clean_df["Av_68U"] = df_merged["Av_68U"]
clean_df["evstate"] = df_merged["evstate_x"]

In [31]:
cols_of_int = ['RA', 'DEC', 'feh', 'afe', 'age', 'age_68L',
               'age_68U', 'mass', 'mass_68L', 'mass_68U', 'dist', 'dist_68L',
               'dist_68U', 'Av', 'Av_68L', 'Av_68U', 'evstate']

In [32]:
clean_df[cols_of_int] = clean_df[cols_of_int].apply(pd.to_numeric)

In [33]:
clean_df.head(10)

,APOGEE_ID,KIC,RA,DEC,feh,afe,age,age_68L,age_68U,mass,mass_68L,mass_68U,dist,dist_68L,dist_68U,Av,Av_68L,Av_68U,evstate
0,2M19222920+3710285,1569842,290.62167,37.17460,-0.24068,0.11591,9.8244,7.8523,12.5843,1.0016,0.9332,1.0584,619.0364,609.5228,628.7579,0.0722,-0.0065,0.1449,1
1,2M19300513+3717470,1726291,292.52139,37.29641,-0.34123,0.18947,10.1218,8.0353,12.8233,0.9791,0.9228,1.0471,1169.8991,1152.1260,1187.8505,0.4291,0.3483,0.4950,1
2,2M19045380+3741230,2283721,286.22419,37.68973,-0.19160,0.11233,9.4182,7.4989,12.0439,1.0143,0.9593,1.0891,1675.7610,1650.0607,1701.1031,0.2961,0.2050,0.3550,1
3,2M19060736+3740100,2284679,286.53070,37.66945,-0.44800,0.20509,11.2142,9.0157,14.0133,0.9394,0.8897,1.0045,588.3684,580.0962,596.8570,0.0741,0.0018,0.1349,1
4,2M19280882+3736381,2305590,292.03679,37.61060,-0.29561,0.23539,10.2088,8.2604,12.4406,1.0264,0.9543,1.0714,1071.7846,1058.6198,1085.1445,0.3414,0.2793,0.3849,1
5,2M19250117+3742537,2442483,291.25490,37.71492,-0.14234,0.11806,10.0423,7.8523,12.6677,1.0182,0.9507,1.0814,1662.2511,1636.4770,1688.4423,0.3717,0.2923,0.4450,1
6,2M19261694+3745527,2443903,291.57060,37.76465,-0.54019,0.23100,12.6354,10.1158,15.8693,0.9183,0.8550,0.9691,1092.7903,1076.4651,1107.9102,0.1675,0.1050,0.2369,1
7,2M19202341+3749231,2568912,290.09755,37.82309,-0.08835,0.15876,10.3729,8.2224,13.2054,1.0275,0.9549,1.0857,1243.5205,1223.2071,1261.7639,0.3824,0.3050,0.4554,1
8,2M19271735+3755229,2714785,291.82233,37.92304,-0.12793,0.17066,10.9534,8.7217,13.9646,1.0068,0.9375,1.0637,1059.0146,1042.3656,1075.2456,0.1943,0.1192,0.2749,1
9,2M19025956+3802049,2831815,285.74821,38.03472,-0.18460,0.16398,11.2469,9.4406,14.3738,0.9670,0.9274,1.0422,1831.5956,1806.5495,1855.7016,0.2760,0.2150,0.3409,1

In [53]:
clean_df.to_csv('../data/andrea_merged_clean.csv')

> check if the data I am currently using for analysis is the same as this one

In [35]:
df_test = pd.read_csv("/Users/ioanaciuca/Desktop/MasterFolder/P3_revision/data/Rcut_andrea_data_proc.csv")

In [37]:
df_test.head(10)

,Unnamed: 0,APOGEE_ID,KIC,RA,DEC,FE_H,A_FE,age,age_68L,age_68U,mass,mass_68L,mass_68U,dist,dist_68L,dist_68U,Av,Av_68L,Av_68U,evstate
0,0,2M19252021+3647118,1027337,291.33421,36.78664,0.27517,0.02257,6.0138,4.8417,7.5603,1.2304,1.1658,1.3181,1232.9190,1214.5069,1251.6686,0.2401,0.1750,0.3141,1
1,1,2M19241746+3651460,1161447,291.07278,36.86280,0.05792,-0.00560,4.9287,4.1697,6.0934,1.2459,1.1694,1.3278,2255.7231,2238.4626,2272.4140,0.3725,0.3450,0.4121,2
2,2,2M19261297+3648265,1163621,291.55407,36.80738,0.02810,0.00514,1.8968,1.7069,1.9719,1.6968,1.6748,1.7767,1634.0474,1620.3166,1646.2237,0.3717,0.3350,0.4202,2
3,3,2M19250718+3654252,1294122,291.27992,36.90702,-0.00896,0.00458,4.1563,3.2810,5.1864,1.3129,1.2397,1.4059,1268.5159,1249.4245,1286.7348,0.2381,0.1550,0.2977,1
4,4,2M19252149+3654097,1294385,291.33955,36.90270,0.10649,-0.01105,4.0969,3.2734,5.1570,1.3546,1.2705,1.4399,638.8773,630.2312,649.1202,0.0822,0.0150,0.1534,1
5,5,2M19264481+3658152,1296068,291.68673,36.97090,0.04340,0.06081,13.5655,10.5245,16.4069,0.9604,0.9134,1.0326,1603.4676,1583.0692,1626.7709,0.3691,0.2950,0.4177,1
6,6,2M19270812+3657217,1296507,291.78385,36.95604,0.02192,-0.00709,2.9060,2.3692,3.7587,1.4407,1.3614,1.5447,1602.2674,1579.4288,1627.1003,0.2987,0.2250,0.3645,1
7,7,2M19225688+3702125,1429505,290.73700,37.03682,-0.05295,0.01624,7.7573,5.9566,10.1207,1.1089,1.0222,1.1747,1229.1167,1207.2855,1248.7865,0.3909,0.3063,0.4750,1
8,8,2M19243068+3701290,1431059,291.12787,37.02473,0.10757,0.03383,7.7268,6.0954,9.6702,1.1272,1.0567,1.1974,1254.0539,1235.4921,1272.0456,0.4455,0.3743,0.5149,1
9,9,2M19264298+3704199,1433593,291.67912,37.07222,0.15737,-0.00669,2.4670,2.0184,3.1391,1.5650,1.4700,1.6670,1159.0739,1141.5635,1177.1031,0.2423,0.1892,0.3348,1

In [38]:
test = pd.merge(clean_df, df_test, on="APOGEE_ID")

In [52]:
print((test["age_x"] - test["age_y"]).value_counts())

 0.000000e+00    3258
 1.776357e-15      12
-8.881784e-16      10
-1.776357e-15       7
-4.440892e-16       5
 1.110223e-16       2
-2.220446e-16       1
 2.220446e-16       1
 8.881784e-16       1
dtype: int64